[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Serve file .html senza redirect
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"
